### ISSUE TITLE
How do i send RAW Packet?

### ISSUE THREAD

**Issue by GuckTubeYT** [eikarna/gotops#1]
Hello, how do I send a raw packet? Thanks 🙏
And can you make some documentation, please? Thanks 🙏

**Comment by eikarna** [comment]
Currently there is no contributor for documentation. But you can see example at [WorldPacket.go](https://github.com/eikarna/gotps/blob/main/handler/WorldPacket/WorldPacket.go) or [TankPacket.go](https://github.com/eikarna/gotps/blob/main/handler/TankPacket/TankPacket.go)
